name: 'airbyte_facebook_ads'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_facebook_ads:
    materialized: table
    tmp:
      materialized: view

vars:
  facebook_ads_schema: "facebook_marketing_airbyte_masch"
  airbyte_facebook_ads:
    ads: "{{ source('airbyte_facebook_ads','ads') }}"
    ad_creative: "{{ source('airbyte_facebook_ads','ad_creative') }}"
    ad_creatives: "{{ source('airbyte_facebook_ads','ad_creatives') }}"
    ad_insights: "{{ source('airbyte_facebook_ads','ad_insights') }}"
    campaigns: "{{ source('airbyte_facebook_ads','campaigns') }}"