name: 'airbyte_intercom'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_intercom:
    materialized: table
    tmp:
      materialized: view

vars:
  airbyte_intercom:
    contacts: "{{ source('airbyte_intercom','contacts') }}"
    companies: "{{ source('airbyte_intercom','companies') }}"
    companies_plan: "{{ source('airbyte_intercom','companies_plan') }}"
    conversations: "{{ source('airbyte_intercom','conversations') }}"
    conversation_parts: "{{ source('airbyte_intercom','conversation_parts') }}"
