version: 2

sources:
  - name: airbyte_facebook_ads
    schema: "{{ var('facebook_ads_schema', 'facebook_marketing_airbyte_masch') }}"
    database: "{% if target.type != 'spark'%}{{ var('facebook_ads_database', target.database) }}{% endif %}"
    tables:
      - name: ads
      - name: ads_creative
      - name: ad_creatives
      - name: ads_insights
      - name: campaigns

models:
  - name: facebook_ads__ad_set_report
    description: >
      This model shows the number of impressions, clicks and spend for each adset.
    columns:
      - name: date_day
        description: The date of the ad, adset or campaign.
        tests:
          - not_null
      - name: account_id
        description: The unique id of the account.
        tests:
          - not_null
      - name: account_name
        description: The name of the account.
        tests:
          - not_null
      - name: campaign_id
        description: The unique id of the campaign.
        tests:
          - not_null
      - name: campaign_name
        description: The name of the campaign.
        tests:
          - not_null
      - name: adset_id
        description: The unique id of the adset.
        tests:
          - not_null
      - name: adset_name
        description: The name of the adset.
        tests:
          - not_null
      - name: impressions
        description: The number of times the ad/adset/campaign was shown.
      - name: clicks
        description: The number of clicks the ad/adset/campaign received.
      - name: spend
        description: The amount of money spent on the ad/adset/campaign.
       

  - name: facebook_ads__ad_campaign_report
    description: >
      This model shows the number of impressions, clicks and spend for each campaign.
    columns:
      - name: date_day
        description: The date of the ad, adset or campaign.
        tests:
          - not_null
      - name: account_id
        description: The unique id of the account.
        tests:
          - not_null
      - name: account_name
        description: The name of the account.
        tests:
          - not_null
      - name: campaign_id
        description: The unique id of the campaign.
        tests:
          - not_null
      - name: campaign_name
        description: The name of the campaign.
        tests:
          - not_null
      - name: impressions
        description: The number of times the ad/adset/campaign was shown.
      - name: clicks
        description: The number of clicks the ad/adset/campaign received.
      - name: spend
        description: The amount of money spent on the ad/adset/campaign.
  
  metrics:
  - name: total_adset_spend
    label: Total spend by adset
    model: ref('facebook_ads__ad_set_report')
    description: "The amount spent on each adset"

    type: sum
    sql: spend

    timestamp: date_day
    time_grains: [day, week, month]

    dimensions:
      - adset_name
      - campaign_name
      - account_name

  - name: total_adset_clicks
    label: Total clicks by adset
    model: ref('facebook_ads__ad_set_report')
    description: "The number of clicks on each adset"

    type: sum
    sql: clicks

    timestamp: date_day
    time_grains: [day, week, month]

    dimensions:
      - adset_name
      - campaign_name
      - account_name

  - name: total_adset_impressions
    label: Total impressions by adset
    model: ref('facebook_ads__ad_set_report')
    description: "The number of impressions on each adset"

    type: sum
    sql: impressions

    timestamp: date_day
    time_grains: [day, week, month]

    dimensions:
      - adset_name
      - campaign_name
      - account_name

  - name: total_campaign_spend
    label: Total impressions by adset
    model: ref('facebook_ads__campaign_report')
    description: "The amount spend on each campaign"

    type: sum
    sql: spend

    timestamp: date_day
    time_grains: [day, week, month]

    dimensions:
      - ad_name
      - campaign_name
      - account_name

  - name: total_campaign_clicks
    label: Total clicks by adset
    model: ref('facebook_ads__campaign_report')
    description: "The number of clicks on each campaign"

    type: sum
    sql: clicks

    timestamp: date_day
    time_grains: [day, week, month]

    dimensions:
      - ad_name
      - campaign_name
      - account_name

  - name: total_campaign_impressions
    label: Total impressions by adset
    model: ref('facebook_ads__campaign_report')
    description: "The number of impressions on each campaign"

    type: sum
    sql: impressions

    timestamp: date_day
    time_grains: [day, week, month]

    dimensions:
      - ad_name
      - campaign_name
      - account_name